apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/lsst-sqre/strimzi-registry-operator
    newTag: 0.5.0rc1

resources:
  - registry-crd.yaml
  - rbac.yaml
  - deployment.yaml
