apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: strimzischemaregistries.roundtable.lsst.codes
spec:
  scope: Namespaced
  group: roundtable.lsst.codes
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: >-
            StrimziSchemaRegistry represents a desired Schema Registry instance
          type: object
          properties:
            spec:
              type: object
              description: >-
                The specification of the Schema Registry instance.
              properties:
                strimzi-version:
                  type: string
                  default: "v1beta2"
                  description: >-
                    The version of the Strimzi Custom Resource API to use. The
                    correct value depends on the deployed version of Strimzi.
                listener:
                  type: string
                  default: "internal"
                  description: >-
                    The name of the Kafka listener to use to connect.
  names:
    kind: StrimziSchemaRegistry
    plural: strimzischemaregistries
    singular: strimzischemaregistry
    shortNames:
      - ssrs
      - ssr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-registry-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: strimzi-registry-operator
rules:
- apiGroups:
  - roundtable.lsst.codes
  resources:
  - strimzischemaregistries
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - deployments
  - services
  verbs:
  - list
  - watch
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: strimzi-registry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: strimzi-registry-operator
subjects:
- kind: ServiceAccount
  name: strimzi-registry-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-registry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-registry-operator
    template:
      metadata:
        labels:
          app: strimzi-registry-operator
      spec:
        containers:
        - image: lsstsqre/strimzi-registry-operator:build
          imagePullPolicy: Always
          name: operator
        serviceAccountName: strimzi-registry-operator
  strategy:
    type: Recreate
