apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: strimzischemaregistries.roundtable.lsst.codes
spec:
  scope: Namespaced
  group: roundtable.lsst.codes
  preserveUnknownFields: false
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: >-
            StrimziSchemaRegistry represents a desired Schema Registry instance
          type: object
          properties:
            spec:
              type: object
              description: >-
                The specification of the Schema Registry instance.
              properties:
                strimziVersion:
                  type: string
                  default: "v1beta2"
                  description: >-
                    The version of the Strimzi Custom Resource API to use. The
                    correct value depends on the deployed version of Strimzi.
                strimzi-version:
                  type: string
                  default: "v1beta2"
                  description: >-
                    Deprecated. Use strimziVersion instead.
                listener:
                  type: string
                  default: "tls"
                  description: >-
                    The name of the Kafka listener to use to connect.
                serviceType:
                  type: string
                  default: "ClusterIP"
                  description: >-
                    The type of service to create for the registry. Default is
                    ClusterIP. Can be NodePort to publish the registry
                    externally.
                registryImage:
                  type: string
                  default: "confluentinc/cp-schema-registry"
                  description: >-
                    The Docker image for the Confluent Schema Registry.
                registryImageTag:
                  type: string
                  default: "5.3.1"
                  description: >-
                    The Docker image tag for the Confluent Schema Registry.
                    Use this property to control the version of the deployed
                    schema registry.
  names:
    kind: StrimziSchemaRegistry
    plural: strimzischemaregistries
    singular: strimzischemaregistry
    shortNames:
      - ssrs
      - ssr
